esphome:
  name: pura-mini
  friendly_name: Pura Mini
  on_boot:
    - priority: -100
      then:
      - output.turn_off: heater_output
    - priority: 200
      then:
        - climate.control:
            id: heater_climate
            custom_preset: "Medium"
            
esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components
    components: [ st25r3918 ]

st25r3918:
  id: nfc_reader
  irq_pin: GPIO13
  sda_pin: 27
  scl_pin: 14
  update_interval: 500ms
  carts:
    - cart_id: "E002080AA155AA6F"
      name: "Lemon"

text_sensor:
  - platform: st25r3918
    fragrance_name:
      name: "Fragrance name"
    cart_id:
      name: "Cart ID"

binary_sensor:
  - platform: st25r3918
    tag_present:
      name: "Cart present"

  - platform: gpio
    id: setup_button
    name: "Setup Button"
    pin:
      number: GPIO4
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms

    on_multi_click:
      # Short press: simple restart
      - timing:
          - ON for at most 1s
          - OFF for at least 200ms
        then:
          - logger.log: "Short press: Restarting..."
          - button.press: restart_btn

      # Long press (5s): factory reset to provisioning mode
      - timing:
          - ON for at least 5s
        then:
          - logger.log: "Long press: Entering setup mode..."
          # stop heat first
          - switch.turn_off: diffuser_switch
          - output.turn_off: heater_output

          # flush usage so you don't lose up to ~60 seconds
          - lambda: |-
              id(nfc_reader).flush_usage();

          # poison stored wifi so it *must* fall back to AP next boot
          - wifi.configure:
              ssid: "___PURA_SETUP___"
              password: ""
              save: true
          - delay: 500ms
          - button.press: restart_btn

sensor:
  - platform: st25r3918
    usage_time:
      name: "Fragrance runtime"
    scent_remaining:
      name: "Fragrance remaining"

  - platform: adc
    id: thermistor_adc
    name: "Thermistor ADC"
    pin: GPIO36
    attenuation: 12db
    update_interval: 5s

  - platform: resistance
    id: thermistor_resistance
    name: "Thermistor Resistance"
    sensor: thermistor_adc
    configuration: UPSTREAM
    resistor: 5.36kOhm         

  - platform: ntc
    id: heater_temperature
    name: "Heater Temperature"
    sensor: thermistor_resistance
    unit_of_measurement: "°C"
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 58kOhm
    on_value_range:
      - above: 90.0
        then:
          - logger.log: "SAFETY: Overtemp! Shutting heater down."
          - output.turn_off: heater_output
          - script.stop: heater_timer
          - climate.control:
              id: heater_climate
              mode: "OFF"
          - globals.set:
              id: heater_on
              value: 'false'
          - lambda: 'id(nfc_reader).set_heating(false);'
          - select.set:
              id: diffuse_timer
              option: "Off"

logger:
  level: WARN

api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

wifi:
  ap:
    ssid: "Pura-Mini"
    password: "..."
    ap_timeout: 15s

captive_portal:

output:
  - platform: gpio
    id: heater_output
    pin: GPIO21

climate:
  - platform: thermostat
    id: heater_climate
    internal: false
    sensor: heater_temperature
    default_preset: Medium
    on_boot_restore_from: memory
    heat_deadband: 1°C
    heat_overrun: 1°C
    min_heating_off_time: 10s
    min_heating_run_time: 10s
    min_idle_time: 0s
    
    visual:
      min_temperature: 20°C
      max_temperature: 90°C
      temperature_step: 1°C
    
    heat_action:
      - if:
          condition:
            lambda: 'return id(heater_on);'
          then:
            - logger.log:
                format: "THERMOSTAT: HEAT ON"
                level: WARN
            - output.turn_on: heater_output

    idle_action:
      - if:
          condition:
            lambda: 'return id(heater_on);'
          then:
            - logger.log:
                format: "THERMOSTAT: IDLE"
                level: WARN
            - output.turn_off: heater_output
        
    preset:
      - name: Subtle
        default_target_temperature_low: 63°C
      - name: Medium
        default_target_temperature_low: 71°C
      - name: Strong
        default_target_temperature_low: 80°C

globals:
  - id: heater_on
    type: bool
    restore_value: false
    initial_value: 'false'

select:
  - platform: template
    name: "Fragrance Strength"
    id: strength_select
    icon: "mdi:gauge"
    optimistic: true
    options: ["Subtle", "Medium", "Strong"]
    initial_option: "Medium"
    on_value:
      then:
        - climate.control:
            id: heater_climate
            custom_preset: !lambda 'return x;'
        - if:
            condition:
              lambda: 'return id(heater_on);'
            then:
              - light.turn_on:
                  id: top_leds
                  brightness: !lambda |-
                    if (x == "Subtle") return 0.33f;
                    if (x == "Strong") return 1.0f;
                    return 0.66f;

  - platform: template
    name: "Diffuse Timer"
    id: diffuse_timer
    icon: "mdi:timer-outline"
    optimistic: true
    options:
      - "Off"
      - "15 minutes"
      - "30 minutes"
      - "1 hour"
    initial_option: "Off"
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x == "Off" && id(heater_on);'
            then:
              - script.stop: heater_timer
              - switch.turn_off: diffuser_switch
        - if:
            condition:
              lambda: 'return x == "15 minutes";'
            then:
              - script.execute:
                  id: heater_timer
                  duration_min: 15
        - if:
            condition:
              lambda: 'return x == "30 minutes";'
            then:
              - script.execute:
                  id: heater_timer
                  duration_min: 30
        - if:
            condition:
              lambda: 'return x == "1 hour";'
            then:
              - script.execute:
                  id: heater_timer
                  duration_min: 60
button:
  - platform: restart
    id: restart_btn
    name: "Reprovision"

switch:
  - platform: template
    name: "Diffuser"
    id: diffuser_switch
    icon: "mdi:scent"
    restore_mode: RESTORE_DEFAULT_OFF
    lambda: 'return id(heater_on);'
    turn_on_action:
      - globals.set:
          id: heater_on
          value: 'true'
      - lambda: 'id(nfc_reader).set_heating(true);'
      - climate.control:
          id: heater_climate
          mode: HEAT
      - light.turn_on:
          id: top_leds
          brightness: !lambda |-
            auto strength = id(strength_select).current_option();
            if (strength == "Subtle") return 0.33f;
            if (strength == "Strong") return 1.0f;
            return 0.66f;
          red: 1.0
          green: 0.5
          blue: 0.0
    turn_off_action:
      - globals.set:
          id: heater_on
          value: 'false'
      - lambda: 'id(nfc_reader).set_heating(false);'
      - climate.control:
          id: heater_climate
          mode: "OFF"
      - output.turn_off: heater_output
      - script.stop: heater_timer
      - light.turn_off: top_leds
      - select.set:
          id: diffuse_timer
          option: "Off"
      
script:         
  - id: heater_timer
    mode: restart
    parameters:
      duration_min: int
    then:
      - switch.turn_on: diffuser_switch
      - delay: !lambda "return duration_min * 60 * 1000;"
      - switch.turn_off: diffuser_switch
      - select.set:
          id: diffuse_timer
          option: "Off"

light:
  - platform: esp32_rmt_led_strip
    name: "Button LED"
    id: button_led
    pin: GPIO15
    num_leds: 1
    rgb_order: RGB
    chipset: WS2812
    entity_category: config

  - platform: esp32_rmt_led_strip
    name: "Top LEDs"
    id: top_leds
    pin: GPIO22
    num_leds: 2
    rgb_order: GRB
    chipset: WS2812
    entity_category: config
